export const sports = ['American Football', 'Archery'
    , 'Arm Wrestling', 'Auto Racing'
    , 'BMX', 'Badminton'
    , 'Baseball', 'Basketball'
    , 'Bobsledding', 'Bodyboarding'
    , 'Bowling', 'Boxing'
    , 'Canoeing', 'Capture the Flag'
    , 'Competitive Dancing', 'Cricket'
    , 'Cross-country Skiing', 'Curling'
    , 'Cycling', 'Diving'
    , 'Dodgeball', 'Dragon Boat Racing'
    , 'Electronic Sports', 'Field Hockey'
    , 'Figure Skating', 'Fishing'
    , 'Footbag (Hacky Sack)', 'Football (Soccer)'
    , 'Frisbee', 'Gliding'
    , 'Golf', 'Gymnastics'
    , 'Hang Gliding', 'Hide and Seek'
    , 'Hiking', 'Horse Racing'
    , 'Ice Fishing', 'Ice Hockey'
    , 'Inline Skating', 'Kayaking'
    , 'Keep Away', 'Lacrosse'
    , 'Logrolling', 'Luge'
    , 'Martial Arts', 'Miniature Golf'
    , 'Mountaineering', 'Outrigger Canoeing'
    , 'Paragliding', 'Polo'
    , 'Racquetball', 'Rafting'
    , 'Ringette', 'Rock Climbing'
    , 'Roller Skating', 'Rowing'
    , 'Rugby', 'Running'
    , 'Sailing', 'Skateboarding'
    , 'Skydiving', 'Snorkelling'
    , 'Snowboarding', 'Snowshoeing'
    , 'Squash', 'Street Hockey'
    , 'Sumo', 'Surfing'
    , 'Swimming', 'Table Tennis'
    , 'Tag', 'Tennis'
    , 'Tobogganing', 'Track & Field'
    , 'Trampolining', 'Triathlon'
    , 'Unicycling', 'Volleyball'
    , 'Wakesurfing', 'Walking'
    , 'Water Polo', 'Weightlifting'
    , 'Windsurfing', 'Wood Chopping'
    , 'Wrestling']